[IMP] academy: creating-a-basic-module, the-browser, templates t#59945
JJRR5/Vauxoo-Slides pull request #1
Opened 2022-09-09 23:21 UTC by JJRR5

This PR is reference to [T#59945](https://www.vauxoo.com/web#id=59945&action=464&active_id=17&model=project.task&view_type=form&cids=1&menu_id=1490)

**Issue**
The main goal of this PR is: 
1. Understand how the controllers works
2. Understand and learn the basic about templates

**What change**
- Created a controller call Academy with a method called index that renders teacher's information
- Created demo data that is render by the controller 
- Created a Teachers model that is going to store the demo data in the DB

**Evidence** 
![image](https://user-images.githubusercontent.com/76703666/189457961-6c332cdd-f635-4f4c-b6f5-7a92da1215d5.png)

2022-09-09 23:21 UTC, JJRR5 commented
@sebasdrk17 could you please check?

2022-09-12 15:19 UTC, sebasdrk17 commented on academy/controllers/main.py
> +    @http.route('/academy/academy/', auth='public', website=True)
```suggestion
    @http.route('/academy/get_teachers', auth='public', website=True)
```

2022-09-12 15:19 UTC, sebasdrk17 commented on academy/controllers/main.py
>      def index(self, **kw):
```suggestion
    def get_teachers(self, **kw):
```

2022-09-12 15:19 UTC, sebasdrk17 commented on academy/controllers/main.py
> +        Teachers = http.request.env['academy.teachers']
```suggestion
        teachers = http.request.env['academy.teachers']
```

2022-09-12 15:21 UTC, sebasdrk17 commented on academy/controllers/main.py
> +    @http.route('/academy/<name>', auth='public', website=True)
```suggestion
    @http.route('/academy/get_by_name/<name>', auth='public', website=True)
```

2022-09-12 15:22 UTC, sebasdrk17 commented on academy/controllers/main.py
> +        return '<h1>%s</h1>' % name
What's the purpose of this controller? just to print the given name on a page??

2022-09-12 15:23 UTC, sebasdrk17 commented on academy/controllers/main.py
> +    @http.route('/academy/<name>', auth='public', website=True)
```suggestion
    @http.route('/academy/teacher/<name>', auth='public', website=True)
```

2022-09-12 15:32 UTC, sebasdrk17 commented on academy/controllers/main.py
> +        return '<h1>{} ({})</h1>'.format(id, type(id).__name__)
Use concatenation by % instead

```suggestion
        return '<h1>%s (%s)</h1>' % (id, type(id).__name__)
```

I also don't get why we are returning the id and the type of the id

2022-09-12 15:33 UTC, sebasdrk17 commented on academy/controllers/main.py
> +    @http.route('/academy/<model("academy.teachers"):teacher>', auth='public', website=True)
```suggestion
    @http.route('/academy/get_teacher_by_model/<model("academy.teachers"):teacher>', auth='public', website=True)
```

2022-09-12 15:34 UTC, sebasdrk17 commented on academy/controllers/main.py
> +    def obj_teacher(self, teacher):
```suggestion
    def render_teacher(self, teacher):
```

2022-09-12 15:34 UTC, sebasdrk17 commented on academy/models/__init__.py
> +from . import models
use a better name instead of just models

2022-09-12 15:35 UTC, sebasdrk17 commented on academy/views/templates.xml
> +            <t t-set="title">Academy</t>
Why are you using `t-set`?

2022-09-12 15:36 UTC, sebasdrk17 commented on academy/views/templates.xml
> +            <div class="oe_structure"/>
why is this here?

2022-09-12 15:37 UTC, sebasdrk17 commented on academy/views/views.xml
> +        <field name="name">Academy Teachers:Form</field>
use proper naming for views

2022-09-12 15:37 UTC, sebasdrk17 commented on academy/views/views.xml
> +            <form action="">
remove action

2022-09-12 15:38 UTC, sebasdrk17 commented on academy/views/views.xml
> +    <menuitem id="menu_academy_content_teachers" action="action_academy_teachers" parent="menu_academy_content"/>
If there is only going to be one menu, concatenate the menuitems instead

2022-09-12 15:39 UTC, sebasdrk17 commented on academy/__manifest__.py
> +        'security/ir.model.access.csv',
if you delete this file, this should no te be here

2022-09-12 15:39 UTC, sebasdrk17 requested changes
First chunk of comments

2022-09-12 16:03 UTC, JJRR5 commented on academy/controllers/main.py
> +        return '<h1>%s</h1>' % name
yes, just that, should I keep it or remove it ?

2022-09-12 16:04 UTC, JJRR5 commented on academy/controllers/main.py
> +        return '<h1>{} ({})</h1>'.format(id, type(id).__name__)
The purpose of this controller is to show that controllers can validate data

2022-09-12 16:13 UTC, JJRR5 commented on academy/views/templates.xml
> +            <t t-set="title">Academy</t>
I'm not sure yet because I don't know if Oscar is gonna use that for something else

2022-09-12 16:14 UTC, sebasdrk17 commented on academy/controllers/main.py
> +        return '<h1>%s</h1>' % name
Leave it, I just wanted to know if that was intended

2022-09-12 16:16 UTC, sebasdrk17 commented on academy/views/templates.xml
> +            <t t-set="title">Academy</t>
Remove the t-set, it is not needed here (and is declared incorrectly)

2022-09-12 16:16 UTC, sebasdrk17 commented
I also forgot to mention that you need to add docstring to your controllers so we know what they do

2022-09-12 16:42 UTC, JJRR5 commented on academy/views/templates.xml
> +            <div class="oe_structure"/>
I missed to delete that tag

2022-09-12 16:59 UTC, JJRR5 commented
@sebasdrk17 could you please check?

2022-09-12 17:04 UTC, sebasdrk17 commented on .eslintrc.json
> +    "yoda": "error"
this whole file should not be here.

2022-09-12 18:00 UTC, sebasdrk17 commented on academy/controllers/main.py
> +        """returns the given name with the h1 tag"""
create docstring based on [this](https://sphinx-rtd-tutorial.readthedocs.io/en/latest/docstrings.html)

2022-09-12 18:02 UTC, sebasdrk17 commented on academy/models/teachers.py
> +class Teachers(models.Model):
classes always needs to be declared as singular

```suggestion
class Teacher(models.Model):
```

2022-09-12 18:03 UTC, sebasdrk17 requested changes
second chunk of comments

2022-09-12 20:49 UTC, JJRR5 commented on academy/controllers/main.py
> +        """returns the given name with the h1 tag"""
![image](https://user-images.githubusercontent.com/76703666/189755911-f8fb97ae-0be1-4da7-9601-bc12ded53205.png)
based on this controller, what kind of data is the render than I am returning?

2022-09-12 21:08 UTC, JJRR5 commented
@sebasdrk17 could you please check?

2022-09-12 21:10 UTC, sebasdrk17 commented on academy/controllers/main.py
> +        """returns the given name with the h1 tag"""
The return needs to be more specific, renders what?

2022-09-12 21:44 UTC, JJRR5 commented on academy/controllers/main.py
> +        """returns the given name with the h1 tag"""
I already modified that description to be more specific

2022-09-12 21:47 UTC, sebasdrk17 commented on .eslintrc.json
> +    "yoda": "error"
@JJRR5 this needs to be deleted

2022-09-12 21:48 UTC, sebasdrk17 commented on .eslintrc.json
> +    "yoda": "error"
you have to delete the remote file, check this (second comment): https://stackoverflow.com/questions/7927230/remove-directory-from-remote-repository-after-adding-them-to-gitignore

2022-09-12 21:50 UTC, sebasdrk17 commented on academy/controllers/main.py
> +        :type teacher: str or int
Since you are declaring the teacher as a `academy.teachers` the type is not str neither int (unless is accepted)

the correct type should be `academy.teachers` because the controller is expecting a recorset of that model

2022-09-12 21:51 UTC, sebasdrk17 commented on academy/models/teachers.py
> +    _name = 'academy.teachers'
this is still not changed, it has to be teacher not teachers

```suggestion
    _name = 'academy.teacher'
```

2022-09-12 21:51 UTC, sebasdrk17 requested changes
third chunk of code

2022-09-12 22:17 UTC, JJRR5 commented
changes tested and corrected, @sebasdrk17 could you please check?

2022-09-12 22:36 UTC, sebasdrk17 approved these changes
LGTM could you check please? @andreaarce

2022-09-12 23:42 UTC, andreaarce approved these changes

2022-09-13 15:22 UTC, merged